CREATE TABLE Airfare (
    Airfare_ID NUMBER PRIMARY KEY,
    Flight_ID NUMBER REFERENCES Flight(Flight_ID),
    Fare_Amount NUMBER
);

DESCRIBE AIRFARE;


INSERT INTO Airfare VALUES (1, 1, 150);
INSERT INTO Airfare VALUES (2, 2, 200);
INSERT INTO Airfare VALUES (3, 3, 300);
INSERT INTO Airfare VALUES (4, 4, 180);
INSERT INTO Airfare VALUES (5, 5, 120);

SELECT * FROM AIRFARE;
