CREATE TABLE Transaction(
T_ID INT,
T_Type VARCHAR(10),
Departure_date DATE,
Booking_date DATE,
E_ID INT,
P_ID INT,
F_ID VARCHAR(10),
Charge_Amount INT,
PRIMARY KEY(T_ID),
FOREIGN KEY(E_ID) REFERENCES Employee(E_ID),
FOREIGN KEY(P_ID) REFERENCES Passengers(P_ID),
FOREIGN KEY(F_ID) REFERENCES Flight(F_ID),
FOREIGN KEY(Charge_Amount) REFERENCES AirFare(Charge_Amount)
);

DESCRIBE TRANSACTION;
SELECT * FROM TRANSACTION;
